export const GUNDANIUM_GAME_ABI = [
  {
    type: "function",
    name: "startPVE",
    inputs: [
      { name: "cardTokenId", type: "uint256" },
      { name: "arcId", type: "uint256" },
    ],
    outputs: [{ name: "sessionId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settleBattle",
    inputs: [
      { name: "sessionId", type: "uint256" },
      { name: "winner", type: "address" },
      { name: "finalHpWinner", type: "uint16" },
      { name: "timestamp", type: "uint256" },
      { name: "signature", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimPVEReward",
    inputs: [{ name: "sessionId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pveEntryFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sessions",
    inputs: [{ name: "sessionId", type: "uint256" }],
    outputs: [
      { name: "player1", type: "address" },
      { name: "player2", type: "address" },
      { name: "card1TokenId", type: "uint256" },
      { name: "card2TokenId", type: "uint256" },
      { name: "gndmStaked", type: "uint256" },
      { name: "battleType", type: "uint8" },
      { name: "status", type: "uint8" },
      { name: "arcId", type: "uint256" },
      { name: "winner", type: "address" },
      { name: "createdAt", type: "uint64" },
      { name: "rewardClaimed", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pveCampaignProgress",
    inputs: [{ name: "player", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "arcGndmReward",
    inputs: [{ name: "arcId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  // ── PVP ────────────────────────────────────────────────────────────────────
  {
    type: "function",
    name: "startPVP",
    inputs: [
      { name: "cardTokenId", type: "uint256" },
      { name: "stakeAmount", type: "uint256" },
    ],
    outputs: [{ name: "sessionId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "joinPVP",
    inputs: [
      { name: "sessionId", type: "uint256" },
      { name: "cardTokenId", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pvpMinStake",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pvpFeePercent",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPVPQueue",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]" }],
    stateMutability: "view",
  },
  // ── Events ─────────────────────────────────────────────────────────────────
  {
    type: "event",
    name: "PVEStarted",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "sessionId", type: "uint256", indexed: true },
      { name: "arcId", type: "uint256", indexed: false },
      { name: "cardTokenId", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PVPStarted",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "sessionId", type: "uint256", indexed: true },
      { name: "cardTokenId", type: "uint256", indexed: false },
      { name: "stake", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PVPJoined",
    inputs: [
      { name: "player", type: "address", indexed: true },
      { name: "sessionId", type: "uint256", indexed: true },
      { name: "cardTokenId", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BattleSettled",
    inputs: [
      { name: "sessionId", type: "uint256", indexed: true },
      { name: "winner", type: "address", indexed: true },
    ],
  },
] as const;
