export const GUNPLA_CARD_ABI = [
  {
    type: "function",
    name: "mintCard",
    inputs: [
      { name: "to", type: "address" },
      { name: "tokenUri", type: "string" },
      {
        name: "traits",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "series", type: "string" },
          { name: "faction", type: "string" },
          { name: "pilotName", type: "string" },
          { name: "rarity", type: "uint8" },
          { name: "armorType", type: "uint8" },
          { name: "hp", type: "uint16" },
          { name: "primaryWeapon", type: "string" },
          { name: "primaryDamage", type: "uint16" },
          { name: "secondaryWeapon", type: "string" },
          { name: "secondaryDamage", type: "uint16" },
          { name: "tertiaryWeapon", type: "string" },
          { name: "tertiaryDamage", type: "uint16" },
          { name: "specialAttack", type: "string" },
          { name: "specialDamage", type: "uint16" },
          { name: "repaintColor", type: "string" },
          { name: "decalId", type: "string" },
          { name: "frameId", type: "uint8" },
          { name: "colorShift", type: "uint8" },
          { name: "repaintStyle", type: "uint8" },
        ],
      },
    ],
    outputs: [{ name: "tokenId", type: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mintPriceUsdc",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenOfOwnerByIndex",
    inputs: [
      { name: "owner", type: "address" },
      { name: "index", type: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenURI",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTraits",
    inputs: [{ name: "tokenId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "name", type: "string" },
          { name: "series", type: "string" },
          { name: "faction", type: "string" },
          { name: "pilotName", type: "string" },
          { name: "rarity", type: "uint8" },
          { name: "armorType", type: "uint8" },
          { name: "hp", type: "uint16" },
          { name: "primaryWeapon", type: "string" },
          { name: "primaryDamage", type: "uint16" },
          { name: "secondaryWeapon", type: "string" },
          { name: "secondaryDamage", type: "uint16" },
          { name: "tertiaryWeapon", type: "string" },
          { name: "tertiaryDamage", type: "uint16" },
          { name: "specialAttack", type: "string" },
          { name: "specialDamage", type: "uint16" },
          { name: "repaintColor", type: "string" },
          { name: "decalId", type: "string" },
          { name: "frameId", type: "uint8" },
          { name: "colorShift", type: "uint8" },
          { name: "repaintStyle", type: "uint8" },
        ],
      },
    ],
    stateMutability: "view",
  },
] as const;
